In [2]:
import numpy as np

In [4]:
np.random.randn(2)

array([-0.77242624,  0.4426183 ])

In [6]:
np.random.randn(3,2)

array([[-2.72329571,  0.73240031],
       [ 0.83425757, -1.6049751 ],
       [-1.03049807, -1.44758553]])

In [8]:
np.random.randn(5,5,5)

array([[[ 0.87030936,  1.31204456, -0.11775912,  1.37412706,
          2.02928546],
        [ 0.48691437, -1.39383752, -1.17016166,  0.82959832,
          2.4895306 ],
        [ 0.04248466,  1.47984754, -0.34228827,  0.52663023,
         -0.34875874],
        [-0.11629375,  0.73614066, -0.103308  , -1.13832252,
         -0.19245862],
        [ 1.79180163, -0.87891829,  2.73305494,  0.06720411,
          0.073838  ]],

       [[ 1.71455526,  0.82047052, -0.93418112,  1.01548385,
          0.77198264],
        [ 1.17835552,  0.55652653, -2.35030396, -0.31365789,
         -0.29276531],
        [ 0.57863215, -0.43561084, -0.18645693,  0.18670493,
         -1.03561107],
        [-0.96471721, -0.25024505,  0.23274175,  0.63640309,
         -1.53358468],
        [ 0.19608213, -1.50185605,  0.42526701, -0.79407945,
         -0.82634128]],

       [[ 0.62779147, -1.49723034,  0.39772435, -1.2109318 ,
         -0.44910489],
        [ 1.45605883, -0.54285578,  0.85342757,  0.3627247 ,
         -1

In [12]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
np.dot(a,b)

array([[19, 22],
       [43, 50]])

In [14]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
np.dot(b,a)

array([[23, 34],
       [31, 46]])

In [17]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6]])
np.dot(a,b)

ValueError: shapes (2,2) and (1,2) not aligned: 2 (dim 1) != 1 (dim 0)

In [19]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6]])
np.dot(b,a)

array([[23, 34]])

In [22]:
b = np.array([5,6])
print(b)

[5 6]


In [24]:
b = np.array([[5,6]])
print(b)

[[5 6]]


In [26]:
x = np.array([[1,2],[3,4],[5,6]])
np.max(x)

6

In [29]:
y = np.array([1,2,3])
d = np.array([4,5,6])
print(y - d)

[-3 -3 -3]


In [31]:
y = np.array([1,2,3])
d = np.array([4,5,6])
print(np.square(y - d))

[9 9 9]


In [32]:
y = np.array([1,2,3])
d = np.array([4,5,6])
print(np.sum(np.square(y - d)))

27


In [37]:
def sigmoid(x):
    return 1/(1 + np.exp(-x))

In [38]:
a = np.array([-3, -1, 1, 3])
print(sigmoid(a))

[0.04742587 0.26894142 0.73105858 0.95257413]
